name: The Spares Shop
title: The Spares Shop
description: Keeping your appliance going
host: 0.0.0.0

repository: cmbuckley/thesparesshop.co.uk
url: https://thesparesshop.starsquare.co.uk
baseurl: ""

exclude:
  - CNAME
  - Gemfile
  - vendor

sass:
  style: compressed

social:
  facebook: The-Spares-Shop-547368338647016
  twitter: thesparesshop
  email: sales@thesparesshop.co.uk
